version: '3.8'
services:
  geoserver:
    image: registry.antt.gov.br/geoserver/geoserver:2.25.3
    container_name: geoserver
    ports:
      - "8070:8080"
    environment:
      #- GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      #- GEOSERVER_REQUIRE_FILE=/opt/geoserver_data/global.xml
      - GEOSERVER_ADMIN_PASSWORD=admin  # Adicione esta linha com a nova senha
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS="charts,control-flow,css,csw-iso,csw,db2,dxf,excel,feature-pregeneralized,gdal,geopkg-output,grib,gwc-s3,h2,iau,importer,inspire,jp2k,libjpeg-turbo,mapml,mbstyle,metadata,mongodb,monitor,mysql,netcdf-out,netcdf,ogr-wfs,ogr-wps,oracle,params-extractor,printing,pyramid,querylayer,rat,sldservice,sqlserver,vectortiles,wcs2_0-eo,web-resource,wmts-multi-dimensional,wps-cluster-hazelcast,wps-download,wps"
    #volumes:
      #- geoserver_data:/opt/geoserver/data_dir
      #- ./extensions:/opt/geoserver/webapps/geoserver/WEB-INF/lib
volumes:
  geoserver_data: